namespace YUHS.WebAPI.MCare.Staff.Models.Nusing
{
    public class ActList
    {
        public string ChosNo { get; set; }
        public string OrdSeq { get; set; }
        public string DrgInjExecSeq { get; set; }
        public string DrgInjExecSeq2 { get; set; }
        public string ExecGb { get; set; }
        public string PrescGb { get; set; }
        public string DsgCd { get; set; }
        public string WrkShtGbNm2 { get; set; }
        public string OrdTypCd2 { get; set; }
        public string OrdNo2 { get; set; }
        public string OrdCd { get; set; }
        public string RoomBed { get; set; }
        public string PatNm { get; set; }
        public string WrkShtGbNm { get; set; }
        public string ChkBit { get; set; }
        public string ExecYmd { get; set; }
        public string ExecHm { get; set; }
        public string OrdTypCd { get; set; }
        public string OrdNo { get; set; }
        public string OrdNm { get; set; }
        public string OrdNm2 { get; set; }
        public string KubGb { get; set; }
        public string ExecQty { get; set; }
        public string EmerYn { get; set; }
        public string OrdProgLoc { get; set; }
        public string ExecOrdSeq { get; set; }
        public string OrdProgStusNm { get; set; }
        public string OrdYmd { get; set; }
        public string UnitNo { get; set; }
        public string DrgInjExecQty { get; set; }
        public string ChosGb { get; set; }
        public string OrdNm_M { get; set; }
        public string TQty { get; set; }
        public string Qty { get; set; }
        public string Frq { get; set; }
        public string Dcnt { get; set; }
        public string PrescType { get; set; }
        public string TretExecGb { get; set; }
        public string Rmk { get; set; }
        public string ReqInfo { get; set; }
        public string HosiGb { get; set; }
        public string HopYmd { get; set; }
        public string HopHm { get; set; }
        public string RetGb { get; set; }
        public string DcYn { get; set; }
        public string MviGb { get; set; }
        public string OrdSmpLocGb { get; set; }
        public string CntiExamMi { get; set; }
        public string BasCapUnitNm { get; set; }
        public string UskdNm { get; set; }
        public string MedHmDesc { get; set; }
        public string OrdDsgNm { get; set; }
        public string PrescTypeNm { get; set; }
        public string OrdKindNm { get; set; }
        public string OrdSlipCd { get; set; }
        public string MvPhoGbNm { get; set; }
        public string OrdGbNm { get; set; }
        public string ExRsvYmd { get; set; }
        public string ExRsvFrHm { get; set; }
        public string OrdOptNm { get; set; }
        public string SlipOrdNm { get; set; }
        public string SlipCd { get; set; }
        public string CrNo { get; set; }
        public string TPNResnCd { get; set; }
        public string OrdGrGbNm { get; set; }
        public string PrtRmk { get; set; }
        public string PrtOrdNo { get; set; }
        public string PrtRoomBed { get; set; }
        public string PrtOrdYmd { get; set; }
        public string PrtPatNm { get; set; }
        public string PrtOrdSlipCd { get; set; }
        public string NurOrdMemo { get; set; }
        public string Ward { get; set; }
        public string OrdDsgCd { get; set; }
        public string PrtOrdNm { get; set; }
        public string PrtQty { get; set; }
        public string QtyCmptGb { get; set; }
        public string SugaCd { get; set; }
        public string RecoStdBasYn { get; set; }
        public string Yakpumcd { get; set; }
        public string DrgImgPth { get; set; }
        public string OrdProgStus { get; set; }
        public string OrdExecYmd { get; set; }
        public string OrdKindCd { get; set; }
        public string DrgOrdGb { get; set; }
        public string VaccOrdCd { get; set; }
        public string VaccRegYn { get; set; }
        public string AddMtlOrdYn { get; set; }
        public string ClnDeptCd { get; set; }
        public string Refnd { get; set; }
        public string ATCNo { get; set; }
    }
}